cache: pip
dist: xenial
language: python
arch:
  - arm64
  - amd64
sudo: required

python:
    - "3.7"
    - "3.8"

allow_failure:
    - python: "3.8"

install:
    - pip install -r requirements.txt
    - pip freeze

before_script:
    - make prepare
    - uname -m
    #- make install-db

script:
    - make test-ci

after_success:
    - make upload-coverage

deploy:
    provider: script
    script: make upload-pypi
    on:
        python: 3.8
        tags: true

notifications:
    email: false
